# Generated by Django 6.0.5 on 2026-05-22 01:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=512)),
                ('npi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('upin', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('general', models.CharField(blank=True, max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, db_index=True, max_length=255)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('exclusion_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('exclusion_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reinstatement_date', models.DateField(blank=True, null=True)),
                ('waiver_date', models.DateField(blank=True, null=True)),
                ('waiver_state', models.CharField(blank=True, max_length=2)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oig_exclusion',
                'ordering': ['last_name', 'first_name', 'business_name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='exclusion_search_gin'), models.Index(fields=['state', 'exclusion_date'], name='exclusion_state_date_idx'), models.Index(fields=['exclusion_type'], name='exclusion_type_idx'), models.Index(fields=['npi'], name='exclusion_npi_idx')],
            },
        ),
    ]
