# Generated by Django 6.0.5 on 2026-06-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusion',
            name='source',
            field=models.CharField(default='federal', max_length=20),
        ),
    ]
