# Generated by Django 6.0.5 on 2026-06-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusions', '0003_georgiaexclusion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusion',
            name='source',
        ),
    ]
